### ISSUE TITLE
Example of use

### ISSUE THREAD

**Issue by livingbeams** [thcomp/Unity_GoogleMobileVisionSDKWrapper#1]
Do you have any example available where to see how to use your code to make face detection in a Unity project?
Best regards.

**Comment by thcomp** [comment]
Hi livingbeams

This project is not good, because it is very heavy running by memory copy from JVM to native.
If you wanna know how to use it, please check following repository, unity scene and source code.
That repository is test code for Google Tango, so if you wanna work it, please prepare a device for Google Tango.
(Probably I re-make it for Google AR Core in near the future)

BR
---------------------------------
repository:
https://github.com/eq-inc/eq-unity-google-tango

unity scene:
Assets/FaceDetector.unity

source code:
https://github.com/eq-inc/eq-unity-google-tango/blob/master/Assets/Scripts/MobileVisionWrapper/jp/eq_inc/mobilevisionwrapper/Accessor.cs
---------------------------------

**Comment by livingbeams** [comment]
Thank you very much
